{% set version = "0.3.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gdtools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gdtools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gdtools/gdtools_{{ version }}.tar.gz
  sha256: fba6166bdefe742d94f33d8904bf2d66432b063cf426d28b3bef22bcd3cc6698

build:
  merge_build_host: true  # [win]
  ignore_run_exports_from:
    # Only used as a transitive dep from cairo but not linked directly.
    - glib *
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-gfonts                   # [build_platform != target_platform]
    - r-htmltools                # [build_platform != target_platform]
    - r-memoise                  # [build_platform != target_platform]
    - r-rcpp                     # [build_platform != target_platform]
    - r-systemfonts              # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-gfonts
    - r-htmltools
    - r-memoise
    - r-rcpp >=0.12.12
    - r-systemfonts >=0.1.1
    - cairo
    - fontconfig
    - freetype
    # cairo pulls in "libglib" but only "glib" carries GLib's pkg-config files needed here
    - glib *
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-gfonts
    - r-htmltools
    - r-memoise
    - r-rcpp >=0.12.12
    - r-systemfonts >=0.1.1
    - cairo

test:
  commands:
    - $R -e "library('gdtools')"           # [not win]
    - "\"%R%\" -e \"library('gdtools')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=gdtools
  dev_url: https://github.com/davidgohel/gdtools
  license: GPL-3.0-only
  summary: Useful tools for writing vector graphics devices.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
