{% set version = "0.4.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-gdtools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gdtools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gdtools/gdtools_{{ version }}.tar.gz
  sha256: ede74955c7b2de48a4271d524bea27438de0429de7920a1f6202d159f7ef4736

build:
  ignore_run_exports_from:
    # Only used as a transitive dep from cairo but not linked directly.
    - glib *
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-fontquiver                 # [build_platform != target_platform]
    - r-htmltools                  # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - r-systemfonts                # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.12.12
    - r-fontquiver >=0.2.0
    - r-htmltools
    - r-systemfonts >=1.1.0
    - cairo
    - fontconfig
    - freetype
    # cairo pulls in "libglib" but only "glib" carries GLib's pkg-config files needed here
    - glib *
  run:
    - r-base
    - r-rcpp >=0.12.12
    - r-fontquiver >=0.2.0
    - r-htmltools
    - r-systemfonts >=1.1.0
    - cairo

test:
  commands:
    - $R -e "library('gdtools')"           # [not win]
    - "\"%R%\" -e \"library('gdtools')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=gdtools
  dev_url: https://github.com/davidgohel/gdtools
  license: GPL-3.0-only
  summary: Tools are provided to compute metrics of formatted strings and to check the availability
    of a font.  Another set of functions is provided to support the collection of fonts
    from 'Google Fonts' in a cache. Their use is simple within 'R Markdown' documents
    and 'shiny' applications but also with graphic productions generated with the 'ggiraph',
    'ragg' and 'svglite' packages or with tabular productions from the 'flextable' package.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
