{% set version = '0.1.9' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gdtools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gdtools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gdtools/gdtools_{{ version }}.tar.gz
  sha256: 6b8b5f2cee76bba2656316186f0cdf884ab9bde9663c0a66efb860511c8c8e70

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake          # [not win]
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.12.12
    - r-withr
    - cairo
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp >=0.12.12
    - r-withr
    - cairo

test:
  commands:
    - $R -e "library('gdtools')"           # [not win]
    - "\"%R%\" -e \"library('gdtools')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=gdtools
  license: GPL-3
  summary: Useful tools for writing vector graphics devices.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: gdtools
# Version: 0.1.9
# License: GPL-3 | file LICENSE
# Title: Utilities for Graphical Rendering
# Description: Useful tools for writing vector graphics devices.
# Authors@R: c( person("David", "Gohel", , "david.gohel@ardata.fr", c("aut", "cre")), person("Hadley", "Wickham", , "hadley@rstudio.com", "aut"), person("Lionel", "Henry", , "lionel@rstudio.com", "aut"), person("Jeroen", "Ooms", role = "aut", email = "jeroen@berkeley.edu", comment = c(ORCID = "0000-0002-4035-0289")), person("Yixuan", "Qiu", role = "ctb"), person("R Core Team", role = "cph", comment = "Cairo code from X11 device"), person("RStudio", role = "cph") )
# LazyData: TRUE
# Imports: Rcpp (>= 0.12.12), withr
# Suggests: htmltools, testthat, fontquiver (>= 0.2.0), curl
# LinkingTo: Rcpp
# SystemRequirements: cairo
# BugReports: https://github.com/davidgohel/gdtools/issues
# RoxygenNote: 6.1.1
# NeedsCompilation: yes
# Packaged: 2019-06-18 13:13:25 UTC; davidgohel
# Author: David Gohel [aut, cre], Hadley Wickham [aut], Lionel Henry [aut], Jeroen Ooms [aut] (<https://orcid.org/0000-0002-4035-0289>), Yixuan Qiu [ctb], R Core Team [cph] (Cairo code from X11 device), RStudio [cph]
# Maintainer: David Gohel <david.gohel@ardata.fr>
# Repository: CRAN
# Date/Publication: 2019-06-18 13:50:07 UTC
