travis:
  secure:
    BINSTAR_TOKEN: G2p6d42bqJ9waGNG+L3aNS+Fz5iszdO9DmQula+s2NWsriZGQXOHzrSTZVQQ09iHSJkdzADcTjCpEsfT615IWTFgKlZJXr4vMg+nHXdpUd1d6C4OfRKsU5tOXi34zcaG4igqzKyEZAVhr57h+WGBgduCvtHg/Lc8kZlIxAMOrPM8ELV3iC8VXH+G0i1Fd2ILjjMdEjLsetBvGxHAY39bQ0S0LWvjxbEwtfHn2XUG9IxGkmxRkZv5MqUcrs0Pcx2dm/q7oTnsKr14n51sKUfte5hK+12r8lbzj06q1u+W0bTjDalKvruNkCQu6KJK8fpPNBsMtZ+rK3zGIf5t+YArEo9ZPy7oOLU0Cp/U6tm+L8GOl+Lda3yU4ckluCesqd20vU1mbbOjARTwwLIv79gXrQIosfF1WvkbpFLvyjPA7S5KFvf9nmpuRBayZRpnG5LZOR7tmEs6OMv56AndZexxfW3S9LXWtiltB10w1NLExE5fqyppAVUsiC74Xkcq9f0FHKbSSJz+nQKyXG1ymscCbN/kgVIivLygz97LRH26UWmbmqvjLCjE3IlD7VrYtIUrDkyqMWKrpXQiXzgE2fopAt9TfQtPR+BANJD1txtKTl/aqAbl4yTdYOHCgA/Og5KHneghRZPKaRoSdxW4O4Pr8bLSbQsQYBPFMVN0/ykIKO0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
